-- Criação da tabela USUARIOS
CREATE TABLE USUARIOS(
    ID_USUARIO NUMBER(10) PRIMARY KEY NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100)
);

-- Criação da tabela TAREFAS
CREATE TABLE TAREFAS(
    ID_TAREFA NUMBER(10) PRIMARY KEY NOT NULL,
    USUARIO_TAREFA NUMBER(10) NOT NULL,
    TITULO VARCHAR2(200) NOT NULL,
    DESCRICAO VARCHAR2(1000),
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_USUARIO_TAREFA 
        FOREIGN KEY (USUARIO_TAREFA) 
        REFERENCES USUARIOS (ID_USUARIO)
);

-- Sequências para auto incremento
CREATE SEQUENCE USUARIOS_SEQ START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE TAREFAS_SEQ START WITH 4 INCREMENT BY 1;

